#!/bin/sh

WIDTH=1280
HEIGHT=480

INFILE=$1
OUTFILE=$(basename "$INFILE").png

TMPDIR=/tmp/videobarcode
rm -rf "$TMPDIR"
mkdir -p "$TMPDIR"

SECONDS=$(ffprobe -show_format "$INFILE" 2>&1 | grep duration | cut -f2 -d= | cut -f1 -d.)
SECONDS_PER_FRAME=$(echo "$SECONDS/$WIDTH" | bc -l)

ffmpeg -threads auto -i "$INFILE" -an -vf "fps=fps=1/$SECONDS_PER_FRAME, scale=12:ih" "$TMPDIR"/frame%8d.jpg
gm mogrify -resize "1x$HEIGHT!" "$TMPDIR"/*
gm convert "$TMPDIR"/* +append "$OUTFILE"
gm mogrify -resize "$WIDTH!x$HEIGHT!" "$OUTFILE"
