#!/bin/bash

VIDEO="${!#}"

SCREEN_WIDTH=$(xrandr -q | grep Screen | cut -d" " -f8)
SCREEN_HEIGHT=$(xrandr -q | grep Screen | cut -d" " -f10 | sed "s/,//")
NORDLICHT_HEIGHT=60
OSD_H_PX=3
OSD_H=$(python -c "print(100.0*(2*$OSD_H_PX+$NORDLICHT_HEIGHT)/$SCREEN_HEIGHT)") # everybody has python!
OSD_Y=-1 #$(python -c "print(-1+2.0*$NORDLICHT_HEIGHT/($SCREEN_HEIGHT*(1-$OSD_H/100.0)))")

rm -f /tmp/mpv_input.conf
cp -f ~/.mpv/input.conf /tmp/mpv_input.conf 2> /dev/null
echo "n overlay_add 0 0 $OSD_H_PX /tmp/nordlicht.bgra 0 bgra $SCREEN_WIDTH $NORDLICHT_HEIGHT $(($SCREEN_WIDTH*4))
N overlay_remove 0
b osd-bar seek 0" >> /tmp/mpv_input.conf

trap "kill 0" SIGINT SIGTERM EXIT

nordlicht "$VIDEO" -w $SCREEN_WIDTH -h $NORDLICHT_HEIGHT --live -o /tmp/nordlicht.bgra &
{ echo -n "fb"; while true; do echo -n "n"; sleep 0.01; done } | mpv --input-conf=/tmp/mpv_input.conf --osd-border-size=0 --osd-bar-align-y=$OSD_Y --osd-bar-w=100 --osd-bar-h=$OSD_H --osd-duration=3600000 "$@"
